theme: minima
title: STRATOS Towards Excellent Data (TED) Panel
description: Information about the TED Panel and download links to datasets used in STRATOS publications
# Site navigation
navbar_links:
  - title: "Introduction"
    url: "/information/" # Matches the permalink in index.md
  - title: "Data sets"
    url: "/content/" # Matches the permalink in content.md
  - title: "About"
    url: "/about/"   # Matches the permalink in about.md
  
