---
title: "Introduction"
---


# The Towards Excellent Data Panel

The Towards Excellent Data Panel (TEDP) of the <a href="https://www.stratos-initiative.org/" target="_blank">STRATOS initiative</a> has the primary aim to guide members of the STRATOS initiative and other researchers
in establishing principles and applying tools that allow them to obtain and share knowledge about their research data and to use their data sustainably and responsibly.

A secondary aim of TEDP is to establish a repository of data sets that can be used for methodological research and comparisons, including data sets that
have been used in publications of the STRATOS initiative.

## Members

Carsten Oliver Schmidt, University of Greifswald, Germany (Chair)

Georg Heinze, Medical University of Vienna, Austria (Chair)

Willi Sauerbrei, University of Freiburg, Germany 

## Data sets used in STRATOS publications

This website hosts links to all open access data sets that were used in publications of the <a href="https://www.stratos-initiative.org/" target="_blank">STRATOS initiative</a> use. 

Every STRATOS publication that analyzes a dataset is listed here, together with information on how to access the data if it is publicly available.

<i>Last updated: 10-12-2025</i>
